# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7365e7c0c12c727fdb78b6abbbf87a1757fe1dcfd0f9c4c8eab25dbfdc4873f6029c820f97ff049caede5b5148320afa46d5b2e91e8d80f2046e141b8543b55

test:
  secret_key_base: 05db92f10739648bf3c837f84d07c0038e47f7d0e0071ebbb9f4f747b6f5403f4ba3b705682da794c61f5c2ceee3ca17b40697fe2525659b4005f0b26163da7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
